cloc
Thanks for nice utility :+1: 
I've added .cljc extension which is added since clojure 1.7. http://dev.clojure.org/display/design/Reader+Conditionals
=> add support for ClojureC .cljc files

cloc
I moved this to a branch.  See #23.
=> Add functions to tell Forth apart from Fortran and F#.

cloc
AspectJ files (.aj) are commented like Java files.
Language website: https://eclipse.org/aspectj
=> AspectJ support.

cloc
=> Add support for EEx -- Embedded Elixir

README.md
Just for the sake of completeness, but it should.
=> README should mention dnf

cloc
Comments are described at https://laravel.com/docs/5.2/blade#control-structures
=> Blade template language support.

Unix/t/00_C.t, cloc, tests/inputs/FreemarkerTemplate.ftl, tests/outputs/FreemarkerTemplate.ftl.yaml
Add support for Freemarker Template language.
=> Add support for Freemarker Template

Unix/t/00_C.t, cloc, tests/inputs/hello.lua, tests/outputs/hello.lua.yaml
See https://www.lua.org/pil/1.3.html
=> add support for Lua --[[ ]] block comments

Unix/t/00_C.t, cloc, tests/inputs/Mako.mako, tests/outputs/Mako.mako.yaml
See #128 for more details on this pull request.
=> Add extension for mako language

README.md, cloc
About ICE middleware:
https://zeroc.com/
About Slice language:
https://doc.zeroc.com/display/Ice36/The+Slice+Language
=> Slice interface specification language support.

Unix/t/00_C.t, cloc, tests/inputs/Dockerfile, tests/outputs/Dockerfile.yaml
I read some other PR and tried to write support for Dockerfile.
I could not find any docs on how to contribute.
I did the file `Dockerfile.yaml` by hand, but it looks generated. How do I get it?
Do I need something else? Can you help me?
=> Add Dockerfile support

Unix/cloc, Unix/t/00_C.t, cloc, tests/inputs/elixir.ex, tests/outputs/elixir.ex.yaml
Also add a test for Elixir
---
I have to admit, this is the first Perl I wrote in my life, so there might be some stupid mistakes. I modelled the solution after the Python docstring elimination.
=> Consider elixir docs as comments

README.md
Add [Scoop](http://scoop.sh/) toinstallation methods
=> Add Scoop to installation methods

tests/inputs/Gencat-NLS.msg, tests/outputs/Gencat-NLS.msg.yaml
Sorry about making a hash of the test in previous PR - you should have just rejected it...
Have tweaked the test input to fix the line continue test and the expected results,
and fixed the output file to match correctly.
=> fixup the gencat test data and expected result

cloc, tests/inputs/sample.ejs, tests/outputs/sample.ejs.yaml
See [EJS](https://github.com/mde/ejs). It's a template language for HTML.
=> Add EJS support

README.md
=> Fix typo of ssc to scc

cloc
This is a proposed fix for issue #421
=> Fix triple quote refactor commits

Unix/pod2man.mk
Motivation: https://reproducible-builds.org
=> make date reproducible when SOURCE_DATE_EPOCH is set

cloc
Reference https://github.com/AlDanial/cloc/issues/441#issue-542204123
=> New logic forces usage of sdir for git archive creation

README.md
I'm happy that my Hello World Collection helped you develop and test this software. Adding my GitHub URL to my name.
=> Add GitHub URL to user name

.github/workflows/build.yml, Dockerfile
Currently, documentation and cleanup in dockerfile + workflow is missing.
Here an example of how it will look like:
https://github.com/TechMiners/cloc/pull/1
I will continue with documentation and cleanup if you like the idea of using GitHub Actions for CI.
CD could follow in a later step.
=> Feature dockerfile with GitHub Action for running all test and code checks

Dockerfile.build, README.md
When you don't want to install cloc on your machine
=> feat: add dockerfile to distribute an official image

Unix/cloc, cloc
support for black space by replace_regex
=> support for black space by replace_regex

README.md, Unix/NEWS, Unix/cloc, Unix/cloc.1.pod, Unix/t/00_C.t, cloc, tests/outputs/issues/296/results.yaml, tests/outputs/qsort_demo.m.yaml
=> Hyphenate Objective-C

Unix/cloc, Unix/t/00_C.t, cloc, tests/inputs/modules1-func1.pp, tests/inputs/modules1-func2.pp, tests/inputs/modules1-typealias.pp, tests/outputs/modules1-func1.pp.yaml, tests/outputs/modules1-func2.pp.yaml, tests/outputs/modules1-typealias.pp.yaml
Add support for Puppet functions and type aliases.
=> Improve Puppet language matching

README.md, Unix/cloc, Unix/cloc.1.pod, cloc
It took me a little to figure out what the numbers in output file of `--categorized` meant, so I thought it might be worth documenting that.
=> Improve documentation for --categorized flag

Unix/t/00_C.t, cloc, tests/inputs/toml.pest, tests/outputs/toml.pest.yaml
Website: https://pest.rs/
I was not exactly shure what to use for the value in $rh_Scale_Factor so I coppied the value from ANTLR.
=> Add support for Pest grammer files

README.md, Unix/AUTHORS, Unix/cloc, Unix/t/00_C.t, cloc, tests/inputs/Arturo.art, tests/outputs/Arturo.art.yaml
Hi!
I've added support for the Arturo programming language: https://github.com/arturo-lang/arturo
I'm not totally sure if I managed to not mess up - so, if there's anything missing, please let me know and I'll fix it! 😉
=> Add support for Arturo

README.md
https://aur.archlinux.org/packages/cloc-git
=> docs: `cloc-git` AUR package

Unix/cloc, Unix/t/00_C.t, cloc, tests/inputs/orgmode.org, tests/outputs/orgmode.org.yaml
I've added support for the Org Mode: https://orgmode.org
=> Add support for Org Mode

Unix/AUTHORS, Unix/cloc, Unix/t/00_C.t, cloc, tests/inputs/nu-example.nu, tests/inputs/nuon-example.nuon, tests/outputs/nu-example.nu.yaml, tests/outputs/nuon-example.nuon.yaml
Adds support for [Nushell](https://www.nushell.sh/) and its associated data interchange format, [NUON](https://www.nushell.sh/book/loading_data.html#nuon).
=> Add support for Nushell
