AlDanial/cloc

- cloc
Forth comments require whitespace around `\` and `(`.
Test case:
\ comment
\ comment
\code
c\ ode
\code
( comment )
( comment)
(code)
c( ode)
(code)
The same applies `(*`, but this doesn't adress that.
(* comment *)
(*code*)
> Forth requires whitespace around starting comment token.

- cloc
JSON files are processed for Javascript.
CSON files should be processed for Coffeescript as well.
Note that comments are allowed in CSON files.
They are counted and reported in the following example:
```sh
% cloc .                    
10 text files.
10 unique files.                              
5 files ignored.
https://github.com/AlDanial/cloc v 1.65  T=0.05 s (127.7 files/s, 4108.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSON                             5              0             31            140
JSON                             1              0              0             22 …
```
> CSON format support.

- cloc
Stylus language deserves support like CSS or LESS.
Comments are described at https://learnboost.github.io/stylus/docs/comments.html.
> Stylus language support.

- README.md
The previous link was dead.
There seems to be different forks of ohcount, I believe I've pick the one that is most up to date and referenced.
> Update link to ohcount

- cloc
By printing to STDOUT instead of STDERR it gets easier to manipulate the output, for example to pipe it to the pager (without having to redirect in the shell). It's 300+ lines so I needed some paging :smile_cat: 
The [code](https://github.com/AlDanial/cloc/blob/master/cloc#L713) for printing the help contents when sending in nothing is untouched (still an error).
> Print `--help` to STDOUT instead of STDERR

- Unix/cloc
Step to reproduce:
Add to --exclude-list-file=file_list.txt directory with trailing slash.
Expected:
Files in directory with trailing slash are ignored.
Actual result:
Files in directory with trailing slash are not ignored.
> Fixed issue with including files in directory with trailing slash 

- cloc
I noticed the current version of cloc detects some Puppet files as Pascal code (e.g. some files in the openstack-puppet-modules repository) and the other way around (e.g. some files in the freepascal repository). This patch improves the detection rate by tweaking some heuristics.
> Improve heuristics to distinguish between Pascal code and Puppet code

- cloc
I'm using sprockets-es6 in a Rails project for ES6 support, and I realized this tool isn't counting those files.
> Add support for JavaScript in .es6 files

- README.md
The format of the argument in the previous version didn't survive markdown processing - replaced with LANG to match the description.
> Fixing a missing argument to one debug option

- Unix/Makefile
The OpenBSD ports system can be told that a software project needs GNU Make.
This works fine for the main Makefile but fails for generating the man page and the install test
as those targets hard code a call to make instead of `gmake` which stands for GNU Make on
OpenBSD.
This change introduces the $(MAKE) variable which defaults to the make that initiated the Makefile
instead of hard-coding a system wide command.
> Use $(MAKE) instead of hard-coded make

- README.md
If you need any clarification for this contribution I can be reached at email.
MichaelDimmitt@icloud.com
a more in depth description/ example can be found here:
https://github.com/MichaelDimmitt/Bash_Directory_CLOC-Count-Lines-of-Program
program will work appropriately if too much nesting is performed.
However, will miss submost levels if nesting does not exist to reach that level.
each time you nest the command, you access a level deeper into a directory.
This command that I am adding was very useful when I was evaluating a large number of projects on github.
I would put them in a repository. Clone the repository down. And run the allSubdir's command to quickly see how large the different programs were before looking at any of the code.
nice overall program, cheers! Michael Dimmitt
> added to readme; perform Cloc functionality on subLevel of a directory

- Unix/cloc
- Unix/cloc.1.pod
- cloc
Adds documentation for the fact that in-line comments are not
removed by --strip--comments.
Refs #153
> Document idiosyncrazy of --strip-comments

- README.md
On GitHub the README was rendering weirdly.
> Clean up broken heading in README

- Unix/t/00_C.t
- cloc
- tests/inputs/hi.py
- tests/outputs/hi.py.yaml
Add single quoted docstring to tests/inputs/hi.py.
Add Python test output (tests/outputs/hi.py.yaml).
Add Python test entry to Unix/t/00_c.t.
Change docstring_to_C to check for ''' as well as """.
> Add Python Test and Single Quote Docstring

- cloc
Detecting a git hash uses a regular expression to detect a hex sha for a fixed set of {master, HEAD}. This precludes using tags, branch names, relative paths (e.g., HEAD~N, etc.). Rather than
trying to make a hash detection scheme that is bullet proof, this introduces a flag, that the user sets, that forces cloc to interpret *all* values in a diff as git hashes allowing for all valid git hash mechanisms.
There's a distinct possibility that the documentation should be cleaned up. Should it only apply to diff? SHould it apply more broadly?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aldanial/cloc/215)
> Add a --git flag to force git interpretation

- cloc
The 'xml' key is duplicate, should be removed.
> Remove duplicate keys in language extensions.

- Unix/cloc
- cloc
Amended m4 filter definition to make output of --write-lang-def=a
and --force-lang-def=a --write-lang-def=b identical
> Handle replace_between_regex in write_lang_def and read_lang_def

- cloc
Language detection of Objective C/MATLAB/Mathematica/MUMPS and
IDL/QT-Project/Prolog/Proguard was nondeterministic if multiple
languages had the same number of points. For example, cloc produces
different output on each run for the content of the https://github.com/qt/qtquickcontrols
repository.
This change ensures that the result of language detection is always the same for
a given source file.
> make language detection deterministic

- README.md
- cloc
This PR adds support for running multiple cloc processes in order to make cloc work faster on multicore systems. This feature has been tested on Linux and MacOS. The code for using multiple processes is disabled on Windows systems, since it doesn't appear to work reliably in combination with Strawberry Perl.
The PR also includes two other minor changes:
- Cloc now uses fastcwd() instead of cwd() for performance reasons.
- The format of the diff alignment files has changed slightly: the counts for added and removed files now match the number of reported added/removed files.
> Fix issue #22 - performance on multicore systems

- cloc
This should solve issue #252 .
I use 7z instead of WinZip to uncompress git archive file because it's an open source software and is more popular among developers (cloc targeted developers, right?).
However, **this PR need revision before merge** because I came across an issue that perl locks the zip file and 7z can't extract from it. Since my understanding of perl is poor, I had difficulty debugging the 10000 loc perl file so I decided to submit the WIP pull request.
> Add windows support for --git

- Unix/cloc
- cloc
Noticed that the  by-file output in json format from a git archive contains a tempdir as a
prefix, the text output was fine. It looks like the rm_leading_tempdir() calls were missing
for both json and the yaml formats.
> Apply rm_leading_tempdir to yaml and json filename output

- Unix/t/00_C.t
- cloc
- tests/inputs/Gencat-NLS.msg
- tests/inputs/Gencat-NLS.msg.yaml
The gencat utility is a part of the X/Open Portability Guide
and in freebsd the standard suffix .msg is used for the input
files. Set the scale factor to 1.50 but am unsuer if this is
correct, its same used by the 'PO File' translation files. Added
a simple test example based on a modified freebsd file.
Signed-off-by: Alan Robinson <Alan.Robinson@ts.fujitsu.com>
> Add support for gencat NLS Catalogue source files

- cloc
Curly brackets aren't comments in OCaml.
```
(* comment *)
type foobar = {                    
a : int;                       
b : string;                    
}                                  
(* a
multiline 
comment 
*)                                   
let () =                           
let foo = {                      
a=100;                       
b="bar" 
} in                             
Printf.printf "%s %d" foo.b foo.a
```
```
<<<
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
OCaml                            1              1             10              5 …
```
> Don't inherit all Pascal comments for OCaml

- cloc
This PR has two improvements related to the --use-sloccount option:
- Handle unusual filenames correctly (e.g. filenames containing semicolons)
- Support BSD grep (as well as other grep versions that don't have the -P option)
> Improvements --use-sloccount option

- cloc
This makes the output deterministic, which plays nicely with caching
execution.
> Add --hide-rate

- cloc
- tests/inputs/test.idr
- tests/outputs/test.idr.yaml
New comments are supported: block comments, indented documentation comments, indented line comments.
closes #316
> fix: add support for more comments in idris

- cloc
In erlang you can have #! lines with escript which is scripted erlang, so adding to the constants.
> add escript as script language for erlang

- README.md
The Hello World Collection has moved to its own domain, updated the URL. The old URL still works (for now) but is merely a redirect.
> Update URL of Hello World Collection

- cloc
This removes escape sequences when stdout is redirected, e.g. `cloc --help | less`.
It appears escape sequences are only used when printing to stdout anyway.
> Change to STDOUT in terminal check

- README.md
Incomplete sentence in the readme: "This switch forces" should be "This switch forces --csv to be on." to match cloc.1.pod
> Finish incomplete `--csv-delimiter` description

- cloc
In some situations, the output of cloc is nondeterministic. For example, the order of the output can change between runs when counting a project that has the same number of lines of code for multiple languages. 
This change ensures that output is deterministic if cloc is used with the --hide-rate
option, which makes it easier to compare output of multiple runs of cloc.
> Sort output deterministically

- cloc
This ensures that cloc with the --strip-str-comments option handles Kotlin raw strings correctly. 
Example: 
```
fun main(args: Array<String>) {
println("""
/* Hello world */
""")
}
```
The "/* Hello world */" line in the fragment should be counted as code, rather than a comment.
It's probably best to merge this PR after https://github.com/AlDanial/cloc/pull/436, since #436 fixes an edge case that is relevant to Kotlin raw strings.
> Mask comment markers in Kotlin raw strings

- cloc
This PR fixes a bug for an edge case in rm_comments_in_strings where a line ends with a string marker that starts a new multiline string. This issue was introduced inadvertently in https://github.com/AlDanial/cloc/pull/422. I've also added some minor comment and whitespace changes in rm_comments_in_strings in order to improve readability.
The tests I used to check the new version of the subroutine are in https://gist.github.com/stsnel/1838e7b272f7f6cf446d663f08e57e03 .
> Fix strip str comments

- Unix/t/02_git.t
- cloc
- tests/outputs/git_tests/04179b6_ae0d26e.yaml
- tests/outputs/git_tests/f15bf04_d9b6726.yaml
1. Git & Diff now only compares all touch files or commits which only added or deleted files.
2. Git-Diff-Count still stays with the strategy to compare all files.
3. Added also more test.
> #458 fix - Git+diff slower & wrong since 1.84

- Unix/cloc
`*.razor` files are used for ASP.NET Core Blazor WASM (Client-side) components. They have a similar syntax to `*.cshtml` files, including the use of the comment tag set `@* *@`.
I have tested this successfully on a project I am currently developing which uses Blazor WASM components with this file type.
More information on Blazor WASM can be found at the Microsoft Documentation page for it [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#blazor-webassembly).
> Add support for ASP.NET Core Blazor WASM (*.razor)

- README.md
This port is maintained by Joerg Jung (not me) and is of version 1.84. It worked great out of the box on my installation.
Happy hacking!
> Add OpenBSD installation command

- cloc
Slightly decrease timeout and diff_timeout values that are used when user
enters a nonpositive argument value, so that it doesn't cause alarm call
overflows on platforms that apparently use a signed 32 bit integer.
> fix issue #446

- cloc
Fix division by zero when classifying nonreadable files with .b extension.
> fix issue #564: division by zero

- README.md
Remove the extra `-` in  `--docstring-as--code`
> Fix typo in the documentation

- cloc
Hey there, just wanted to add support for the [Denizen (or DenizenScript)](https://denizenscript.com) scripting language.
I am unsure what the language scaling of Denizen is, so I put `0.00`. Hope that is alright. :D
> Added DenizenScript language support.

- README.md
Signed-off-by: JoaoDanielRufino <joaodaniel0405@gmail.com>
- Added gcloc to other counters section on readme
[gcloc](https://github.com/JoaoDanielRufino/gcloc) is a cli written in Go developed by me inspired on cloc cli
> Added gcloc to other counters section on readme

- cloc
Note: This PR doesn't fully resolve the long path issue for Windows. The `File::Find` call will still fail when cloc is given an input with paths > 255 chars. However, the `File::Find` call can be skipped by either using a `--list-file` or by using the `--no-recurse` option.
---
I added wrapper functions for most of the Win32::LongPath things that needed substituting and updated all the existing usages that should need it. I didn't add an explicit flag for enabling this, it just works based off of `$ON_WINDOWS` and `$HAVE_Win32_Long_Path` for now. If you think it'd be better to have a flag to enable it, I could add that instead.
The two cases where it doesn't have wrapper functions is stat/statL and opendir/opendirL. For both of those, the Win32::LongPath version returns different types …
> Add Win32::LongPath to support long paths on Windows

- cloc
This adds a new option `--diff-list-files` which accepts two separate list-files to be diffed.
The main change besides the boilerplate for the new CLI option is the additional case for the `make_file_list` call that uses `read_list_file($ARGV[$i])` as the input (~line 1726).
I also made a couple other changes to make sure that this option can work with `--count-and-diff`:
1. I made it set `$opt_diff = 0` when `$opt_count_diff != 3 and $opt_diff_list_files`. Since `--diff-list-files` automatically sets `$opt_diff = 1`, the first two passes of `--count-and-diff` would attempt to run in diff mode. But since the first two passes are for the individual count runs with a single input, it would fail with the message `Error: incorrect length fh array when preparing diff at step 6.`. I wasn't sure …
> Add --diff-list-files option

- cloc
This fixes #700 (as far as I can tell)
> Remove comments inside OCaml strings

- cloc
This fixes an issue with how the verbose flag is matched in config files. In the current release, it checks for "verbose" or "v" anywhere in the line, instead of only at the beginning of the line. This causes a config like "force-lang Objective-C,h" to match the verbose check instead (because of the v in Objective), if verbose has not already been specified. This changes that check to require v/verbose to be at the start of the line.
> Fix incorrect parsing of config file

- cloc
I needed something to only count files, classified by language. I like subroutines of `cloc` to identify languages but I was not satisfied by the performance drop caused by the line counting on big repositories (Which I do not need in my case). So I propose an option `--only-count-files` to skip line count.
Example on bash mirror repository https://github.com/bminor/bash :
```bash
❯ time ./cloc .
1404 text files.
587 unique files.                                          
868 files ignored.
github.com/AlDanial/cloc v 1.97  T=0.73 s (801.4 files/s, 715967.8 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code …
```
> Add option for file count only

- README.md
Previous link was not working.
> fix link to docker section in README

- Unix/t/00_C.t
If a test fails, the 'got' and 'expected' data is backwards. If
outputs/zos_assembly.s.yaml says 'comment: 30' but results.yaml says
'comment: 0', the test failure output confusingly says that 0 was
expected:
not ok 22 - Assembly 3 results match
Fix this confusing statement by swapping the order such that the data in
outputs/ is expected and the data in results.yaml is got:
not ok 22 - Assembly 3 results match
> Fix labelling of got/expected in test failures

- Unix/cloc
- Unix/t/00_C.t
- cloc
- tests/inputs/PlusCalExample.tla
- tests/inputs/TLAExample.tla
- tests/outputs/PlusCalExample-no-autogen.tla.yaml
- tests/outputs/PlusCalExample.tla.yaml
- tests/outputs/TLAExample.tla.yaml
Recognize .tla files as TLA+ files. Parse PlusCal directives inside TLA+ comments and, if --no-autogen is specified, ignore the PlusCal translator's output within TLA+ files.
> Count lines in TLA+ and PlusCal files

- cloc
Fix for #768: Remove extraneous comma in header after `n_lines` in the JSON report. 
Tested with and without --hide-rate to ensure header still formats correctly.
> Fix for #768: Remove extraneous comma in JSON

- Dockerfile
I did some debugging on why the cpan command was failing. It turns out it was because installing Digest::MD5 relies on a c compiler being present. This resolves the issue by installing gcc. In order to not bloat the image, I've introduced an additional stage purely for the build process (installing dependencies, etc). This also means dos2unix is not included in the final stage, and ca-certificates has also been moved to the test stage (the only stage that actually needs it)
> Fix installing dependencies via cpan in docker

- .github/workflows/build.yml
Since Docker BuildKit became the default build mechanism in Docker, multistage Dockerfiles no longer automatically build all stages. This change forces the test stage to actually run.
Note that this requires #824 to be merged, as currently cpan fails to run due to perl dependencies not being installed into the container
> Fix CI not actually running tests

- cloc
**Describe the bug**  
Files named `Jenkinsfile` or `jenkinsfile` are standard but not recognized as Groovy. Only `.jenkinsfile` are.
**cloc; OS; OS version**  
- cloc version: 2.04  
- OS: Windows or MacOS
- OS version: Windows 11 or  MacOS Sequoia 15.3.2
**To Reproduce**  
1. Create a file named `jenkinsfile` or `Jenkinsfile`.  
2. Run cloc → not recognized as Groovy.  
3. Rename to `.jenkinsfile` → recognized as Groovy.  
**Expected result**  
`Jenkinsfile` and `jenkinsfile` should be recognized as Groovy.
**Additional context**  
Current Groovy definition uses `extension jenkinsfile`. Since `Jenkinsfile` has no extension, it is not matched.
**Proposed solution**  
Keep (for retrocompatibility):  
```
extension jenkinsfile
```
Add:  
```
filename Jenkinsfile
filename jenkinsfile
```
> [fix] Add standard Jenkinsfile filename to be recognized as Groovy files

- README.md
- Unix/NEWS
- Unix/cloc
- cloc
New Languages and File Types:
o Cangjie
o Elixir Script
o Fortran 2003
o Jsonnet
o Nextflow
o Nushell
o Org Mode
o Rego
o UXML, USS (Unity)
Updates:
o First attempt at using Github Actions to package a release including making a Windows executable that works with symlinks as used by winget
o Add column headers for `--show-lang` and `--show-ext` output
o Remove '->' separator in `--show-ext` output
o Remove leading blank space for `--fmt` output written to STDOUT
o New switch `--files-from` as a synonym for `--vcs`
o New switch `--ksep`/`--thousands-delimiter` to show a separator (default is a comma) between thousands in output counts
o Change sequence of Python language filters so that docstrings are handled before `#`
o Jenkinsfile now recognized as Groovy
o Improve Windows/Unix path …
> version 2.06
